spring:
  application:
    name: msa-entity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update       # Cambia a 'validate', 'create', 'none' seg√∫n el entorno
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false

# Puerto del servidor (opcional)
server:
  port: 8080

txlog:
  enabled: true
  topic: txlog.http
  guid-header: X-GUID
  return-guid-header: true
  max-body-bytes: 65536
  store-headers: true
  fail-open: true
  exclude-paths:
    - /actuator
    - /v3/api-docs